export const prompts = [
  "Describe your ideal weekend in detail.",
  "Talk about your favorite childhood memory.",
  "What are your goals for the next year?",
  "Describe a challenging situation you overcame.",
  "Talk about a book or movie that inspired you.",
  "What does success mean to you?",
  "Describe your perfect day from morning to night.",
  "Talk about a person who has influenced you greatly.",
  "What are you most grateful for in your life?",
  "Describe a place you would love to visit and why.",
  "Talk about a skill you would like to learn.",
  "What are your thoughts on work-life balance?",
  "Describe a time you had to make a difficult decision.",
  "Talk about your favorite way to relax and unwind.",
  "What does friendship mean to you?",
  "Describe a moment that changed your perspective.",
  "Talk about a hobby or interest you're passionate about.",
  "What are the most important values in your life?",
  "Describe a memorable trip or vacation.",
  "Talk about something you're proud of accomplishing.",
  "What are your thoughts on technology's impact on society?",
  "Describe a time you stepped out of your comfort zone.",
  "Talk about a cultural tradition that's important to you.",
  "What does 'home' mean to you?",
  "Describe your dream job or career path.",
  "Talk about a lesson you learned from a mistake.",
  "What are your favorite ways to stay motivated?",
  "Describe a person you admire and why.",
  "Talk about your favorite season and what you enjoy about it.",
  "What does 'happiness' mean to you?"
]